<html>
    <head>
        <title><?php echo $this->title; ?></title>
    </head>
    <body style="text-align: center; background-color: #ffffff; color: #000000; font-family: Verdana, Arial, sans-serif; font-size: 12px; margin: 0; padding: 0;">
        <div style="width: 600px; margin-left: auto; margin-right: auto; text-align: left;">
            <div style="margin: 0; padding: 0; margin-bottom: 15px;">
                <img alt="" src="<?php echo $this->assetPath ?>images/header.jpg" />
            </div>
            <div style="margin: 0; padding: 0; margin-bottom: 15px;">
<?php echo $this->content; ?>                
            </div>
            <div style="margin: 0; padding: 0; margin-bottom: 5px;">
                <img alt="" src="<?php echo $this->assetPath ?>images/footer.jpg" />
            </div>
            <div style="margin: 0; padding: 10px; background-color: #ebebea; font-size: 9px;">
<?php echo $this->legal; ?>                
            </div>
        </div>
    </body>
</html>