<!DOCTYPE HTML>
<html>
    <head>
        <title>CBA Fitness</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" href="assets/stylesheets/admin.css" />
        <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.2.0/build/cssgrids/grids-min.css">
        <script src="http://yui.yahooapis.com/3.2.0/build/yui/yui-min.js"></script>
        <script src="assets/scripts/admin/ui.js"></script>
    </head>
    <body style="text-align: center; padding: 20px; font-family: Verdana, sans-serif;">
        <div style="margin-left: auto; margin-right: auto;">
<?php if ($this->fubar) include ANAIZ_VIEW_PATH . 'partial/fubar.phtml'; ?>
            <div id="admin-main" style="padding-top: 20px; padding-left: 0;">
<?php echo $this->content ?>
            </div>
        </div>
    </body>
</html>
