<script src="assets/scripts/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
        
        var savedStatus = true;
        
        function myChangeEvent(i) {
            if (savedStatus) {
                YUI().use('node', function(Y) {
                    Y.all('#editor-form .save-button').set('innerHTML', 'Mentés').set('title', 'Cikk mentése.').removeClass('disabled-button');
                    Y.one('#message-area').set('innerHTML', '');
                });
                savedStatus = false;
            }
        }
        
        
        function myFileBrowser (field_name, url, type, win) {
            var cmsURL = 'http://dev.anaiz.hu/profibban2/utility.php';
            var browserAction = 'articlebrowser';
            if ('image' == type) {
                browserAction = 'imagebrowser';
            }
            if (cmsURL.indexOf("?") < 0) {
                cmsURL = cmsURL + "?id=" + browserAction;
            }
            else {
                cmsURL = cmsURL + "&id=" + browserAction;
            }

            tinyMCE.activeEditor.windowManager.open({
                file : cmsURL,
                title : 'Tallózás a szerveren',
                width : 400,
                height : 300,
                resizable : "yes",
                inline : "yes",
                close_previous : "yes"
            }, {
                window : win,
                input : field_name
            });
            return false;
        }

        tinyMCE.init({
            language : "hu",
            mode : "textareas",
            theme : "advanced",
            plugins : "paste,inlinepopups,searchreplace",
            //content_css : 'assets/stylesheets/editor.css',
            dialog_type : 'modal',
            paste_retain_style_properties : 'none',
            paste_remove_spans : true,
            paste_remove_styles : true,
            entity_encoding : 'raw',
            inline_styles : true,
            relative_urls : false,
            
            onchange_callback : "myChangeEvent",
            //file_browser_callback : 'myFileBrowser',  
            
<?php if (!$this->enableEditing): ?>
            readonly : true,
<?php endif; ?>
            
            //skin : "o2k7",
            //skin_variant : "black",
            width : "100%",
            height : "500px",

            // Theme options - button# indicated the row# only
            theme_advanced_buttons1 : "bold,italic,underline,fontselect,fontsizeselect,forecolor,backcolor,|,link,unlink,|,bullist,numlist,outdent,indent,|,justifyleft,justifycenter,justifyright,|,cut,copy,paste,|,undo,redo,|,search,replace,|,removeformat,code",
            theme_advanced_buttons2 : "",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_blockformats : 'p,h1,h2,h3',
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : false,
        });
    
</script>

<form id="editor-form" method="post" action="<?php echo Request::link('hirlevel', 'uzenet', array('uzenet' => $this->data['id'])); ?>">
    
<?php if ($this->enableEditing): ?>
    <input type="hidden" id="document-save-status" name="document-save-status" value="1" />
<?php endif; ?>    
    <input type="hidden" id="form-id" name="form-id" value="mail-save" />
    <input type="hidden" id="submit-type" name="submit-type" value="save" />
    
    <div class="editor-header">
        <label for="subject"><a href="<?php echo $this->backButton['link']; ?>"><strong><?php echo ucfirst($this->backButton['label']); ?> mappa</strong></a> &gt; Tárgy:</label>
<?php if ($this->enableEditing): ?>
        <input type="text" class="text" id="subject" name="subject" value="<?php echo $this->data['subject'] ?>" />
<?php else: ?>
        <span><strong><?php echo $this->data['subject'] ?></strong></span>
        <input type="hidden" id="subject" name="subject" value="<?php echo $this->data['subject'] ?>" />
<?php endif; ?>
        
<?php if (Mail::DRAFT == $this->data['status']): ?>
        <div class="editor-header-buttons">
            <a class="button submit-button save-button disabled-button" title="Legutóbbi mentés óta nincs móodsítva." href="#editor-form">Elmentve</a>
            <a class="button live-send-button send-button confirm-button submit-button " title="Hírlevél küldése. FIGYELEM! A CÍMLISTA ÖSSZEÁLLÍTÁSA PERCEKIG IS ELTARTHAT, EZ ALATT NEM SZABAD KILÉPNI VAGY FRISSÍTENI A BÖNGÉSZŐ ABLAKOT!!!" href="#">Küldés!</a>
            <a class="button test-send-button send-button submit-button" title="Teszt hírlevél küldése." href="#">Teszt</a>
            <a class="button trash-button submit-button" title="Hírlevél kidobása a kukába." href="#">Kuka</a>
        </div>
<?php elseif (Mail::TRASH == $this->data['status']): ?>
        <div class="editor-header-buttons">
            <a class="button submit-button save-button" title="Levél áthelyezése a piszkozatok közé." href="#editor-form">Kiszedés a kukából</a>
            <a class="button submit-button delete-button" title="Levél végleges törlése." href="#delete-form">Törlés</a>
        </div>
<?php endif; ?>            
        
    </div>

    <div id="message-area">
    <?php if ($this->warning): ?>
            <div class="warining">
                <p><?php echo $this->warning ?></p>
            </div>
    <?php endif; ?>
    <?php if ($this->message): ?>
            <div class="message">
                <p><?php echo $this->message ?></p>
            </div>
    <?php endif; ?>
    </div>

    <div class="document-body">
        <textarea id="body" name="body">
            <?php echo stripslashes($this->data['body']); ?>
        </textarea>
    </div>

    <div class="editor-footer">
<?php if (Mail::DRAFT == $this->data['status']): ?>
        <div class="editor-header-buttons">
            <a class="button submit-button save-button disabled-button" title="Legutóbbi mentés óta nincs móodsítva." href="#editor-form">Elmentve</a>
            <a class="button live-send-button send-button confirm-button submit-button " title="Hírlevél éles küldése." href="#">Küldés!</a>
            <a class="button test-send-button send-button submit-button" title="Teszt hírlevél küldése." href="#">Teszt</a>
            <a class="button trash-button submit-button" title="Hírlevél kidobása a kukába." href="#">Kuka</a>
        </div>
<?php elseif (Mail::TRASH == $this->data['status']): ?>
        <div class="editor-header-buttons">
            <a class="button submit-button save-button" title="Levél áthelyezése a piszkozatok közé." href="#editor-form">Kiszedés a kukából</a>
            <a class="button submit-button delete-button" title="Levél végleges törlése." href="#delete-form">Törlés</a>
        </div>
<?php endif; ?>            
        <p>Visszalépés ide: <a href="<?php echo $this->backButton['link']; ?>"><strong><?php echo ucfirst($this->backButton['label']); ?> mappa</strong></a></p>
    </div>
    
</form>

<form id="delete-form" method="post" action="<?php echo Request::link('hirlevel', 'uzenet', array('uzenet' => $this->data['id'])); ?>">
    <input type="hidden" id="form-id" name="form-id" value="mail-delete" />
</form>    
    
<br /><br />

