<div id="admin-login">
    <h1>Bejelentkezés</h1>
    <form id="login-form" method="post" action="<?php echo Request::link('tag', 'login'); ?>">
        <label for="email">Email: </label>
        <input type="text" class="text" id="email" name="email" value="<?php echo $this->data['email'] ?>" />

        <label for="password">Jelszó: </label>
        <input type="password" class="text" id="password" name="password" />

        <div class="button-panel">
            <a class="submit-button" title="Bejelentkezés" href="#login-form">Bejelentkezés</a>
            <a class="cancel-button" title="Mégsem" href="/index.php">Mégsem</a>
        </div>
    </form>
</div>

